#
# Docker compose file for REDSCAN.
# Warning : The following port are reserved to dockprom monitoring 
# - 3000
# - 9090
# - 9093
# - 9091
#
version: "3.8"
services:

  #redscan-nuclei-exposure:
  #  image: docker.pkg.github.com/certmichelin/redscan-nuclei-exposure/redscan-nuclei-exposure:3.1.1
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-nuclei-exposure:/conf
  #  depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy

  #redscan-nuclei-exposedpanels:
  #  image: docker.pkg.github.com/certmichelin/redscan-nuclei-exposedpanels/redscan-nuclei-exposedpanels:3.1.1
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-nuclei-exposedpanels:/conf
  #  depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy

  #redscan-nuclei-misconfiguration:
  #  image: docker.pkg.github.com/certmichelin/redscan-nuclei-misconfiguration/redscan-nuclei-misconfiguration:3.1.0
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-nuclei-misconfiguration:/conf
  #  depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy
          
  #redscan-nuclei-miscellaneous:
  #  image: docker.pkg.github.com/certmichelin/redscan-nuclei-miscellaneous/redscan-nuclei-miscellaneous:3.1.0
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-nuclei-miscellaneous:/conf
  #  depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy
          
  #redscan-nuclei-technologies:
  #  image: docker.pkg.github.com/certmichelin/redscan-nuclei-technologies/redscan-nuclei-technologies:3.1.0
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-nuclei-technologies:/conf
  #  depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy
          
  #redscan-securitytxt:
  #  image: docker.pkg.github.com/certmichelin/redscan-securitytxt/redscan-securitytxt:3.1.1
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-securitytxt:/conf
  #  depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy
   
  #redscan-puppeteer:
  #  image: docker.pkg.github.com/certmichelin/redscan-puppeteer/redscan-puppeteer:3.1.1
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-puppeteer:/conf
  #  depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy
          
  #redscan-urlcrazy:
  #  image: docker.pkg.github.com/certmichelin/redscan-urlcrazy/redscan-urlcrazy:3.0.1
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-urlcrazy:/conf
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #    elasticsearch:
  #      condition: service_healthy

  #redscan-certinfo:
  #  image: docker.pkg.github.com/certmichelin/redscan-certinfo/redscan-certinfo:3.1.1
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-certinfo:/conf
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #    elasticsearch:
  #      condition: service_healthy
        
  #redscan-cloudenum:
  #    image: docker.pkg.github.com/certmichelin/redscan-cloudenum/redscan-cloudenum:3.0.1
  #    env_file:
  #      - data/environments/red.env
  #    volumes:
  #      - ./logs:/logs
  #      - ./conf/redscan-cloudenum:/conf
  #    depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy

  #redscan-reversewhois:
  #    image: docker.pkg.github.com/certmichelin/redscan-reversewhois/redscan-reversewhois:3.0.0
  #    env_file:
  #      - data/environments/red.env
  #    volumes:
  #      - ./logs:/logs
  #      - ./conf/redscan-reversewhois:/conf
  #    depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      elasticsearch:
  #        condition: service_healthy

  #redscan-alerts:
  #  image: docker.pkg.github.com/certmichelin/redscan-alerts/redscan-alerts:3.0.0
  #  env_file:
  #    - data/environments/red.env
  #    - data/environments/alerts.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-alerts:/conf
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #    elasticsearch:
  #      condition: service_healthy

  #redscan-vulnerability:
  #  image: docker.pkg.github.com/certmichelin/redscan-vulnerability/redscan-vulnerability:3.0.0
  #  env_file:
  #    - data/environments/red.env
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-vulnerability:/conf
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #    elasticsearch:
  #      condition: service_healthy

  #redscan-cache:
  #  image: docker.pkg.github.com/certmichelin/redscan-cache/redscan-cache:3.0.0
  #  volumes:
  #    - ./logs:/logs
  #    - ./conf/redscan-cache:/conf
  #  depends_on:
  #    rabbitmq:
  #      condition: service_healthy
  #    elasticsearch:
  #      condition: service_healthy

  #redscan-cname:
  #  image: docker.pkg.github.com/certmichelin/redscan-cname/redscan-cname:3.0.0
  #  env_file:
  #    - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-cname:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-exploretld:
  #   image: docker.pkg.github.com/certmichelin/redscan-exploretld/redscan-exploretld:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-exploretld:/conf
  #     - ./data/wordlists:/wordlists
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-gitgrabber:
  #   image: docker.pkg.github.com/certmichelin/redscan-gitgrabber/redscan-gitgrabber:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-gitgrabber/log4j2:/conf
  #     - ./conf/redscan-gitgrabber/app/config.py:/usr/bin/gitgrabber/config.py
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-ip:
  #   image: docker.pkg.github.com/certmichelin/redscan-ip/redscan-ip:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-ip:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-masscan:
  #   image: docker.pkg.github.com/certmichelin/redscan-masscan/redscan-masscan:3.1.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-masscan:/conf
  #     - ./data/wordlists:/wordlists
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-nmapservice:
  #   image: docker.pkg.github.com/certmichelin/redscan-nmapservice/redscan-nmapservice:3.1.2
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-nmapservice:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-s3scanner:
  #   image: docker.pkg.github.com/certmichelin/redscan-s3scanner/redscan-s3scanner:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-s3scanner/log4j2:/conf
  #     - ./conf/redscan-s3scanner/app:/root/.aws
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-shodan:
  #   image: docker.pkg.github.com/certmichelin/redscan-shodan/redscan-shodan:3.1.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-shodan:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-slack:
  #   image: docker.pkg.github.com/certmichelin/redscan-slack/redscan-slack:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-slack:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-subfinder:
  #   image: docker.pkg.github.com/certmichelin/redscan-subfinder/redscan-subfinder:3.0.1
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-subfinder/log4j2:/conf
  #     - ./conf/redscan-subfinder/app:/root/.config/subfinder
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-deepsubjack:
  #   image: docker.pkg.github.com/certmichelin/redscan-deepsubjack/redscan-deepsubjack:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-deepsubjack/log4j2:/conf
  #     - ./conf/redscan-deepsubjack/app:/root/.config/subfinder
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-subjack:
  #   image: docker.pkg.github.com/certmichelin/redscan-subjack/redscan-subjack:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-subjack:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-sslscan:
  #   image: docker.pkg.github.com/certmichelin/redscan-sslscan/redscan-sslscan:3.1.1
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-sslscan:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-wappalyzer:
  #   image: docker.pkg.github.com/certmichelin/redscan-wappalyzer/redscan-wappalyzer:3.1.2
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-wappalyzer:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-amass:
  #   image: docker.pkg.github.com/certmichelin/redscan-amass/redscan-amass:3.0.1
  #   env_file:
  #     - data/environments/red.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-amass/log4j2:/conf
  #     - ./conf/redscan-amass/app/:/root/.config/amass/
  #     - ./data/wordlists:/wordlists
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  # redscan-magellan:
  #   image: docker.pkg.github.com/certmichelin/redscan-magellan/redscan-magellan:3.0.0
  #   env_file:
  #     - data/environments/red.env
  #     - data/environments/magellan.env
  #   volumes:
  #     - ./logs:/logs
  #     - ./conf/redscan-magellan:/conf
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     elasticsearch:
  #       condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      # - "exposé:inner"
      - "9200:9200"
    #volumes:
    #  - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
    healthcheck:
        test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
        interval: 20s
        retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=false
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
      interval: 10s
      retries: 20
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibanasetup:
    image: curlimages/curl:7.74.0
    volumes:
      - ./data/kibana:/tmp/
    depends_on:
      kibana:
        condition: service_healthy
    restart: "no"
    entrypoint: "find"
    command: "/tmp/ -iname *.ndjson -exec curl -X POST http://kibana:5601/api/saved_objects/_import?overwrite=true  -H \"kbn-xsrf: true\" --form file=@{} \\;"

  rabbitmq:
    image: rabbitmq:management
    environment: 
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  keycloak:
    image: jboss/keycloak
    env_file:
      - data/environments/keycloak.env
    volumes:
      - ./conf/keycloak/:/conf/
      - ./logs/keycloak/:/opt/jboss/keycloak/standalone/log/
  
  # redscan-rproxy: 
  #   image: docker.pkg.github.com/certmichelin/redscan-rproxy/redscan-rproxy:3.0.0
  #   volumes:
  #     - ./conf/redscan-rproxy/redscan.conf:/usr/local/apache2/conf/redscan.conf
  #     - ./conf/redscan-rproxy/certs/:/usr/local/apache2/conf/certs/
  #     - ./logs/rproxy:/usr/local/apache2/logs/
  #   ports:
  #     - 443:443
  #   extra_hosts:
  #     - ${HOSTNAME}:127.0.0.1
  
