#
# Docker compose file for REDSCAN.
# Warning : The following port are reserved to dockprom monitoring 
# - 3000
# - 9090
# - 9093
# - 9091
#
version: "3.8"
services:

  redscan-amass:
    image: ghcr.io/certmichelin/redscan-amass/redscan-amass:4.0.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-amass/log4j2:/conf
      - ./conf/redscan-amass/app/:/root/.config/amass/
      - ./data/wordlists:/wordlists
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-certinfo:
   image: ghcr.io/certmichelin/redscan-certinfo/redscan-certinfo:4.2.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-certinfo:/conf
   depends_on:
     rabbitmq:
       condition: service_healthy
     elasticsearch:
       condition: service_healthy

  redscan-cloudenum:
     image: ghcr.io/certmichelin/redscan-cloudenum/redscan-cloudenum:4.2.0
     env_file:
       - data/environments/red.env
     volumes:
       - ./logs:/logs
       - ./conf/redscan-cloudenum:/conf
     depends_on:
       rabbitmq:
         condition: service_healthy
       elasticsearch:
         condition: service_healthy

  redscan-cname:
   image: ghcr.io/certmichelin/redscan-cname/redscan-cname:4.0.0
   env_file:
     - data/environments/red.env
   volumes:
    - ./logs:/logs
    - ./conf/redscan-cname:/conf
   depends_on:
    rabbitmq:
      condition: service_healthy
    elasticsearch:
      condition: service_healthy

  redscan-deepsubjack:
    image: ghcr.io/certmichelin/redscan-deepsubjack/redscan-deepsubjack:4.0.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-deepsubjack/log4j2:/conf
      - ./conf/redscan-deepsubjack/app:/root/.config/subfinder
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-exploretld:
    image: ghcr.io/certmichelin/redscan-exploretld/redscan-exploretld:4.0.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-exploretld:/conf
      - ./data/wordlists:/wordlists
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
        
  redscan-gitgrabber:
    image: ghcr.io/certmichelin/redscan-gitgrabber/redscan-gitgrabber:4.2.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-gitgrabber/log4j2:/conf
      - ./conf/redscan-gitgrabber/app/config.py:/usr/bin/gitgrabber/config.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-ip:
    image: ghcr.io/certmichelin/redscan-ip/redscan-ip:4.0.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-ip:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-iprangescanner:
    image: ghcr.io/certmichelin/redscan-iprangescanner/redscan-iprangescanner:4.1.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-iprangescanner:/conf
      - ./data/wordlists:/wordlists
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-masscan:
    image: ghcr.io/certmichelin/redscan-masscan/redscan-masscan:4.1.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-masscan:/conf
      - ./data/wordlists:/wordlists
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-nmapservice:
    image: ghcr.io/certmichelin/redscan-nmapservice/redscan-nmapservice:4.0.1
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-nmapservice:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-nuclei-exposedpanels:
   image: ghcr.io/certmichelin/redscan-nuclei-exposedpanels/redscan-nuclei-exposedpanels:4.2.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-nuclei-exposedpanels:/conf
   depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-nuclei-exposure:
    image: ghcr.io/certmichelin/redscan-nuclei-exposure/redscan-nuclei-exposure:4.2.0
    env_file:
     - data/environments/red.env
    volumes:
     - ./logs:/logs
     - ./conf/redscan-nuclei-exposure:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
   
  redscan-nuclei-miscellaneous:
   image: ghcr.io/certmichelin/redscan-nuclei-miscellaneous/redscan-nuclei-miscellaneous:4.2.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-nuclei-miscellaneous:/conf
   depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-nuclei-misconfiguration:
   image: ghcr.io/certmichelin/redscan-nuclei-misconfiguration/redscan-nuclei-misconfiguration:4.2.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-nuclei-misconfiguration:/conf
   depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-nuclei-technologies:
   image: ghcr.io/certmichelin/redscan-nuclei-technologies/redscan-nuclei-technologies:4.2.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-nuclei-technologies:/conf
   depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-puppeteer:
   image: ghcr.io/certmichelin/redscan-puppeteer/redscan-puppeteer:4.0.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-puppeteer:/conf
   depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-reversewhois:
    image: ghcr.io/certmichelin/redscan-reversewhois/redscan-reversewhois:4.0.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-reversewhois:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-securitytxt:
   image: ghcr.io/certmichelin/redscan-securitytxt/redscan-securitytxt:4.0.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-securitytxt:/conf
   depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-shodan:
    image: ghcr.io/certmichelin/redscan-shodan/redscan-shodan:4.1.0
    env_file:
      - data/environments/red.env
      - data/environments/shodan.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-shodan:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-slack:
    image: ghcr.io/certmichelin/redscan-slack/redscan-slack:4.2.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-slack:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-sslscan:
    image: ghcr.io/certmichelin/redscan-sslscan/redscan-sslscan:4.2.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-sslscan:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-subfinder:
    image: ghcr.io/certmichelin/redscan-subfinder/redscan-subfinder:4.0.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-subfinder/log4j2:/conf
      - ./conf/redscan-subfinder/app:/root/.config/subfinder
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-subjack:
    image: ghcr.io/certmichelin/redscan-subjack/redscan-subjack:4.2.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-subjack:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-urlcrazy:
   image: ghcr.io/certmichelin/redscan-urlcrazy/redscan-urlcrazy:4.2.0
   env_file:
     - data/environments/red.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-urlcrazy:/conf
   depends_on:
     rabbitmq:
       condition: service_healthy
     elasticsearch:
       condition: service_healthy

  redscan-wappalyzer:
    image: ghcr.io/certmichelin/redscan-wappalyzer/redscan-wappalyzer:4.0.0
    env_file:
      - data/environments/red.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-wappalyzer:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
                        
  redscan-magellan:
    image: ghcr.io/certmichelin/redscan-magellan/redscan-magellan:4.2.0
    env_file:
      - data/environments/red.env
      - data/environments/magellan.env
    volumes:
      - ./logs:/logs
      - ./conf/redscan-magellan:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-alerts:
   image: ghcr.io/certmichelin/redscan-alerts/redscan-alerts:4.2.0
   env_file:
     - data/environments/red.env
     - data/environments/alerts.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-alerts:/conf
   depends_on:
     rabbitmq:
       condition: service_healthy
     elasticsearch:
       condition: service_healthy

  redscan-vulnerability:
   image: ghcr.io/certmichelin/redscan-vulnerability/redscan-vulnerability:4.2.0
   env_file:
     - data/environments/red.env
     - data/environments/vulnerability.env
   volumes:
     - ./logs:/logs
     - ./conf/redscan-vulnerability:/conf
   depends_on:
     rabbitmq:
       condition: service_healthy
     elasticsearch:
       condition: service_healthy

  redscan-cache:
   image: ghcr.io/certmichelin/redscan-cache/redscan-cache:4.0.1
   volumes:
     - ./logs:/logs
     - ./conf/redscan-cache:/conf
   depends_on:
     rabbitmq:
       condition: service_healthy
     elasticsearch:
       condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      # - "exposé:inner"
      - "9200:9200"
    #volumes:
    #  - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
    healthcheck:
        test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
        interval: 20s
        retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=false
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
      interval: 10s
      retries: 20
    depends_on:
      elasticsearch:
        condition: service_healthy

  mantisbt:
    image: ghcr.io/certmichelin/redscan-mantisbt/redscan-mantisbt:2.25.2.1
    env_file:
      - data/environments/mantisbt.env
    depends_on:
      - mantisbtdb
    restart: always

  mantisbtdb:
    image: mysql:5.7
    env_file:
      - data/environments/mantisbtdb.env
    volumes:
      - ./data/scripts/mantisbt/bugtracker.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data/mantisbt:/var/lib/mysql
    # Set default collation so Mantis does not complain about latin1
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  kibanasetup:
    image: curlimages/curl:7.80.0
    volumes:
      - ./data/kibana:/tmp/
    depends_on:
      kibana:
        condition: service_healthy
    restart: "no"
    entrypoint: "find"
    command: "/tmp/ -iname *.ndjson -exec curl -X POST http://kibana:5601/api/saved_objects/_import?overwrite=true  -H \"kbn-xsrf: true\" --form file=@{} \\;"

  rabbitmq:
    image: rabbitmq:management
    environment: 
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  keycloak:
    image: jboss/keycloak
    env_file:
      - data/environments/keycloak.env
    volumes:
      - ./conf/keycloak/:/conf/
      - ./logs/keycloak/:/opt/jboss/keycloak/standalone/log/
  
  redscan-rproxy: 
    image: ghcr.io/certmichelin/redscan-rproxy/redscan-rproxy:4.2.0
    volumes:
      - ./conf/redscan-rproxy/redscan.conf:/usr/local/apache2/conf/redscan.conf
      - ./conf/redscan-rproxy/certs/:/usr/local/apache2/conf/certs/
      - ./logs/rproxy:/usr/local/apache2/logs/
    ports:
      - 443:443
    extra_hosts:
      - ${HOSTNAME}:127.0.0.1
  
